= Security Policy

This Eclipse Foundation Project adheres to the https://www.eclipse.org/security/policy/[Eclipse Foundation Vulnerability Reporting Policy].

== How To Report a Vulnerability

If you think you have found a vulnerability in this repository, please report it to us through coordinated disclosure.

*Please do not report security vulnerabilities through public issues, discussions, or change requests.*

Instead, create a https://gitlab.eclipse.org/security/vulnerability-reports/-/work_items/new?issue[confidential]=true[confidential issue] in the Eclipse Foundation Vulnerability Reporting Tracker.

You can find more information about reporting and disclosure at the https://www.eclipse.org/security/[Eclipse Foundation Security page].

Please include as much of the information listed below as you can to help us better understand and resolve the issue:

* The type of issue (e.g., buffer overflow, SQL injection, or cross-site scripting)
* Affected version(s)
* Impact of the issue, including how an attacker might exploit the issue
* Step-by-step instructions to reproduce the issue
* The location of the affected source code (tag/branch/commit or direct URL)
* Full paths of source file(s) related to the manifestation of the issue
* Configuration required to reproduce the issue
* Log files that are related to this issue (if possible)
* Proof-of-concept or exploit code (if possible)

This information will help us triage your report more quickly.

== Supported Versions

The following Eclipse JNoSQL versions are currently supported with security updates:

* 1.1.x
* 1.2.x
