/*
 *  Copyright (c) 2025 Contributors to the Eclipse Foundation
 *   All rights reserved. This program and the accompanying materials
 *   are made available under the terms of the Eclipse Public License 2.0
 *   and Apache License v2.0 which accompanies this distribution.
 *   The Eclipse Public License is available at https://www.eclipse.org/legal/epl-2.0
 *   and the Apache License v2.0 is available at https://www.apache.org/licenses/LICENSE-2.0.
 *
 *   You may elect to redistribute this code under either of these licenses.
 *
 *   Contributors:
 *
 *   Otavio Santana
 */
package org.eclipse.jnosql.mapping.metadata.repository;

import java.util.List;
import java.util.Optional;

/**
 * Provides metadata about a Jakarta Data repository type.
 * This interface is primarily used by Jakarta Data implementations and
 * tooling (e.g., annotation processors, runtime engines, or schema generators)
 * to describe and inspect repository structures, including their entity type,
 * identifier type, and inherited repository interfaces.
 */
public interface RepositoryMetadata {

    /**
     * Returns the entity type handled by this repository, if any.
     *
     * @return an {@link Optional} containing the entity class, or empty if
     * this repository is not parameterized with an entity type.
     */
    Optional<Class<?>> entity();

    /**
     * Retrieves the type of the repository.
     *
     * @return the class type of the repository.
     */
    Class<?> type();

    /**
     * Returns metadata about the declared query methods of this repository.
     * <p>
     * Each method is represented by a {@link RepositoryMethod} instance,
     * describing its signature, parameters, and query derivation strategy.
     *
     * @return a list of {@link RepositoryMethod} descriptors defined in this repository.
     *         The list may be empty but never {@code null}.
     */
    List<RepositoryMethod> methods();

    /**
     * Attempts to resolve the {@link RepositoryMethod} associated with the given {@link MethodKey}.
     * Resolution succeeds only when the key type is compatible with the metadata source (for example,
     * reflective keys cannot match metadata generated by an annotation processor, and name-only keys
     * may be ambiguous when overloading is present). In all such mismatch scenarios this method
     * returns {@link Optional#empty()} rather than throwing, unless an internal inconsistency is
     * detected in the metadata itself.
     *
     * @param key the {@link MethodKey} identifying the method to locate
     * @return an {@link Optional} containing the matching {@link RepositoryMethod}, or empty if no match exists
     */
    Optional<RepositoryMethod> find(MethodKey key);
}
